language: cpp

sudo: false

env:
  matrix:
    - MASON_TEST="unit"
    - MASON_TEST="c_install"
    - MASON_TEST="c_build"
    - MASON_TEST="c_install_symlink_includes"
    - MASON_TEST="cpp11_header_install"
    - MASON_TEST="cpp11_install"
    - MASON_TEST="cpp11_build"
    - MASON_TEST="c_build_android"

install:
# put mason at symlink to simulate historically recommended install method
- mkdir -p custom/path
- sudo ln -s $(pwd)/mason $(pwd)/custom/path/mason
- export PATH=$(pwd)/custom/path:${PATH}

script:
- ./test/${MASON_TEST}.sh
