language: generic

os: linux

sudo: false

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-5-dev' ]

install:
 # put mason at symlink to simulate historically recommended install method
 - mkdir -p custom/path
 - ln -s $(pwd)/mason $(pwd)/custom/path/mason
 - export PATH=$(pwd)/custom/path:${PATH}

script:
 - ./test/unit.sh
 - ./test/c_install.sh
 - ./test/c_install_symlink_includes.sh
 - ./test/cpp11_header_install.sh
 - ./test/cpp11_install.sh
 - export CLANG_VERSION='3.8.0'
 - export CXX=clang++
 - export CC=clang
 - mason install clang ${CLANG_VERSION}
 - export PATH=$(mason prefix clang ${CLANG_VERSION})/bin:${PATH}
 - ./test/c_build.sh
 - ./test/cpp11_build.sh
 - ./test/c_build_android.sh
